# Generated by Django 3.1.7 on 2022-06-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, null=True)),
                ('Facility', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='healthregister.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartingTime', models.CharField(max_length=20, null=True)),
                ('StopingTime', models.CharField(max_length=20, null=True)),
                ('Facility', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='time', to='healthregister.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province', models.CharField(max_length=100, null=True)),
                ('District', models.CharField(max_length=100, null=True)),
                ('Ward', models.CharField(max_length=100, null=True)),
                ('Coordinates', models.CharField(max_length=250, null=True)),
                ('Facility', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='healthregister.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(null=True)),
                ('Facility', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='healthregister.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100, null=True)),
                ('Facility', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='healthregister.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100, null=True)),
                ('Facility', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='healthregister.healthfacility')),
            ],
        ),
    ]
