# Generated by Django 3.1.7 on 2022-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthregister', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='Facility',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='Facility',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Facility',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='Facility',
        ),
        migrations.RemoveField(
            model_name='servicesoffered',
            name='Facility',
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='Coordinates',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='District',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='Province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='Ward',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='equipment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='infrastructure',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='operatingHours',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='phoneNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='services',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ContactInformation',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Infrastructure',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='OperatingHours',
        ),
        migrations.DeleteModel(
            name='ServicesOffered',
        ),
    ]
