# Generated by Django 3.1.7 on 2022-06-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthregister', '0002_auto_20220605_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthfacility',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='healthfacility',
            name='operatingHours',
        ),
        migrations.RemoveField(
            model_name='healthfacility',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='healthfacility',
            name='services',
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=100)),
                ('facility', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='healthregister.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=50)),
                ('hours', models.CharField(blank=True, max_length=100)),
                ('facility', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='healthregister.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(blank=True, max_length=100)),
                ('facility', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='healthregister.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100, null=True)),
                ('facility', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='healthregister.healthfacility')),
            ],
        ),
    ]
