# Generated by Django 3.1.7 on 2022-06-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthregister', '0003_auto_20220606_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='facility',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='healthregister.healthfacility'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='facility',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='healthregister.healthfacility'),
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='facility',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='healthregister.healthfacility'),
        ),
        migrations.AlterField(
            model_name='services',
            name='facility',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='healthregister.healthfacility'),
        ),
    ]
